//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationeryStore.ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Staff3 = new HashSet<Staff>();
            this.StationeryDisbursement = new HashSet<StationeryDisbursement>();
        }
    
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> ContactNameId { get; set; }
        public Nullable<int> AuthorityId { get; set; }
        public Nullable<int> DepartmentRepresentativeId { get; set; }
        public Nullable<long> DelegationStartDate { get; set; }
        public Nullable<long> DelegationEndDate { get; set; }
        public string TelephoneNo { get; set; }
        public string FaxNo { get; set; }
        public Nullable<int> CollectionPointId { get; set; }
    
        public virtual CollectionPoint CollectionPoint { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Staff Staff2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staff3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationeryDisbursement> StationeryDisbursement { get; set; }
    }
}
