//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationeryStore.ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetails
    {
        public int OrderDetailsId { get; set; }
        public int OrderId { get; set; }
        public string ItemCode { get; set; }
        public int QuantityOrdered { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
