//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationeryStore.ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransactionDetails
    {
        public int StockTransDetailId { get; set; }
        public string ItemCode { get; set; }
        public long Date { get; set; }
        public int Quantity { get; set; }
        public int Balance { get; set; }
        public string Type { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
