//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustmentVoucherDetails
    {
        public int AdjustmentId { get; set; }
        public string VoucherId { get; set; }
        public string ItemCode { get; set; }
        public int Quantity { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
    
        public virtual AdjustmentVoucher AdjustmentVoucher { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
