//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationeryRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StationeryRequest()
        {
            this.StationeryRequestDetails = new HashSet<StationeryRequestDetails>();
        }
    
        public string RequestId { get; set; }
        public int StaffId { get; set; }
        public string Status { get; set; }
        public long RequestDate { get; set; }
        public Nullable<int> DecisionById { get; set; }
        public Nullable<long> DecisionDate { get; set; }
        public string Designation { get; set; }
        public string Comment { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationeryRequestDetails> StationeryRequestDetails { get; set; }
    }
}
