//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationeryDisbursement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StationeryDisbursement()
        {
            this.StationeryDisbursementDetails = new HashSet<StationeryDisbursementDetails>();
        }
    
        public int DisbursementId { get; set; }
        public int RetrievalId { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<long> DateDisbursed { get; set; }
        public string Status { get; set; }
        public Nullable<int> CollectionRepId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual StationeryRetrieval StationeryRetrieval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationeryDisbursementDetails> StationeryDisbursementDetails { get; set; }
    }
}
