//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierDetails
    {
        public int SupplierDetailsId { get; set; }
        public string SupplierCode { get; set; }
        public string ItemCode { get; set; }
        public double UnitPrice { get; set; }
        public Nullable<int> SupplierRank { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
